version: '3.0'
services:
    server:
        container_name: riftchat-server
        build:
            context: .
            dockerfile: docker/Dockerfile.server
        volumes:
            - ./src:/src
        ports:
            - "8000:8000"
    client:
        container_name: riftchat-client
        build:
            context: .
            dockerfile: docker/Dockerfile.client
        volumes:
            - ./src:/src
        stdin_open: true
        tty: true
