FROM python:3.9

WORKDIR /src

# There are actually no requirements for the server
# COPY requirements.txt ./
# RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT [ "python", "/src/server.py" ]
